import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import { Dashboard } from "@/components/Dashboard/Dashboard";
import { Sidebar } from "@/components/Sidebar/Sidebar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${inter.className} text-stone-950 bg-stone-100`}>
//         {children}
//       </body>
//     </html>
//   );
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={`${inter.className} min-h-dvh bg-neutral-600`}>
        <div className="mx-auto max-w-[1670px] py-6 lg:py-10">
          <div
            className="rounded-2xl bg-gray-50 ring-1 ring-gray-200 shadow-lg overflow-hidden
            min-h-[calc(100dvh-theme(spacing.24))] 
            grid grid-cols-1 lg:grid-cols-[280px_minmax(0,1fr)]"
          >
            <aside className="p-4">
              <Sidebar />
            </aside>
            <section className="p-3 md:p-4 flex flex-col min-h-0">
              <div className="mt-3 flex-1 min-h-0 overflow-y-auto rounded-2xl bg-white ring-1 ring-gray-200 shadow-md py-2">
                {children}
              </div>
            </section>
          </div>
        </div>
      </body>
    </html>
  );
}
